<?php
/**
 * Created by PhpStorm.
 * User: cardo
 * Date: 2/19/2018
 * Time: 3:29 PM
 */
require_once 'functions.php';
require_once 'config.php';

function voteGenerator($language){
    global $mysqli;
    echo "<meta charset=\"utf-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
    <title>jQuery UI Datepicker - Default functionality</title>
    <link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">
    <link rel=\"stylesheet\" href=\"/resources/demos/style.css\">
    <script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>
    <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>
    <script>
        $( function() {
            $( \"#datepicker\" ).datepicker({ dateFormat: 'yy/mm/dd' });
        } );
    </script>
    <style>
        #elements {
            width:90%;
            -webkit-box-sizing: border-box; /* Safari/Chrome, other WebKit */
            -moz-box-sizing: border-box;    /* Firefox, other Gecko */
            box-sizing: border-box;         /* Opera/IE 8+ */
        }
        #buttons {
            width:45%;
        }
    </style>";
    if ($language == "en"){
        $form = "<form method='post'>
        Steem Username: <input type='text' name='user' value='%s' /></br>
        Date: <input type='text' id='datepicker' name='date' value='%s' /></br>
        Sort by:</br>
          <input type='radio' name='sort' value='author' %s> Author<br>
          <input type='radio' name='sort' value='permlink' %s> Post<br>
          <input type='radio' name='sort' value='weight' %s> Percent<br>
        <input id='buttons' name='generate' type='submit' value='Generate Report' />
        </form>";
        $reportHeader = "# Vote report for @%s on date %s:\n";
        $report2 = "Total Votes: %s\n<br>\nAuthor | Post | Percent\n---- | ---- | ---\n";
        $report3 = "<br>Report generated by [Steem.Place Vote Report Generator](https://steem.place/en/VoteReportGenerator) developed by @moisesmcardona.\nVote him as Witness at [https://steemit.com/~witnesses](https://steemit.com/~witnesses)!";
        $markdownLabel = "Markdown code:</br>";
        $instructions = "Copy and paste the above code into Steemit to post your vote history";
        $notfound = "<b>No votes found for the user or the date specified</b>";
    }
    else{
        $form = "<form method='post'>
        Nombre de usuario en Steem: <input type='text' name='user' value='%s' /></br>
        Fecha: <input type='text' id='datepicker' name='date' value='%s' /></br>
        Ordenar por:</br>
          <input type='radio' name='sort' value='author' %s> Autor<br>
          <input type='radio' name='sort' value='permlink' %s> Post<br>
          <input type='radio' name='sort' value='weight' %s> Porciento<br>
        <input id='buttons' name='generate' type='submit' value='Generar Reporte' />
        </form>";
        $reportHeader = "# Reporte de Voto para @%s el día %s:\n";
        $report2 = "Total de votos: %s\n<br>\nAutor| Post | Porciento\n---- | ---- | ---\n";
        $report3 = "<br>Reporte generado por [el Generador de Reportes de Votos de Steem.Place](https://steem.place/es/GeneradorReporteVotos) desarrollado por @moisesmcardona.\nVótalo como Witness en [https://steemit.com/~witnesses](https://steemit.com/~witnesses)";
        $markdownLabel = "Código Markdown:</br>";
        $instructions = "Copia y Pega el código de arriba en Steemit para postear tu historial de voto.";
        $notfound = "<b>No se han encontrado votos para el usuario o la fecha establecida</b>";
    }
    //Report Generator Variables
    $user='';
    $date='';
    $sort='';
    $author_checked='checked';
    $post_checked='';
    $percent_checked='';
    if(isset($_POST['generate'])){
        $user=$_POST['user'];
        $date=$_POST['date'];
        $sort=$_POST['sort'];
        if ($sort=='author'){
            $author_checked='checked';
            $post_checked='';
            $percent_checked='';
            $sort='author ASC';
        }
        else if ($sort=='permlink'){
            $author_checked='';
            $post_checked='checked';
            $percent_checked='';
            $sort='permlink ASC';
        }
        else if ($sort=='weight'){
            $author_checked='';
            $post_checked='';
            $percent_checked='checked';
            $sort='CAST(weight AS DECIMAL) DESC';
        }
    }
    echo sprintf($form, $user, $date, $author_checked, $post_checked, $percent_checked);
    if(isset($_POST['generate'])){
        $report= sprintf($reportHeader, $user, $date);
        $result = getUserVoteReport($user, $date, $sort, $mysqli);
        if(mysqli_num_rows($result) > 0){
            $report.= sprintf($report2, mysqli_num_rows($result));
            while($row = mysqli_fetch_assoc($result)) {
                $report.="@".$row["author"]." | [".$row["permlink"]."](https://steemit.com/tag/@".$row["author"]."/".$row["permlink"].") | ".$row["weight"]."\n";
            }
            $report.=$report3;
            echo $markdownLabel;
            echo "<textarea  name='body' id='elements' name='body' rows='20'>".$report."</textarea></br>";
            echo $instructions;
        }
        else
            echo $notfound;
    }
}